### ISSUE TITLE
Sharing Graphs

### ISSUE THREAD

**Issue by SNTPG** [omerdemirkan/cs-130-project#7]
## User Story
As a **user**, I would like **to be able to share visualizations** so that **I can give them to colleagues**.

## Detailed Description
Using an event sourcing-based stack, we can store the queries and edits a user makes to their visualization when using the application. We can store this data as a set of instructions used to create the graph, as the graph is purely representational. This should generate a URL which unregistered users can access in a view-only interface.

## Acceptance Criteria
- [x] Given **a registered user clicking the share button on a graph**, the application should both save the instructions to make the visualization and then generate a copyable URL.
- [x] Given **a user accessing the website with a valid URL**, the application should decode the URL and access the appropriate representation that generates the visualization.
- [ ] Given **a user accessing the website with an invalid URL**, the application should display an error modal and return them to the landing page.

**Comment by omerdemirkan** [comment]
Howdie yall, here's the task as I see it.

1. Create a new table in *schema.prisma* to store a shared graph. Because there can be any number of nodes and edges, we can't store each node in a separate column. As I see it, there are 2 options. We can store the nodes and edges as a string with JSON.stringify(nodes), then do JSON.parse(nodesString) to get our node array back. This is janky, but gets the job done. Option 2 is to create tables for *node*, *edge* which have a *graph_id* property on them. When fetching, we can simply query for nodes and edges with the specific graph id.
2. Create a prisma endpoint. This can be with a new router (I'd look at the example router as boilerplate and change things from there). We'll need one endpoint to create a graph in the database (logged in user clicking "share") as a trpc mutation and one endpoint to fetch an existing graph from the database (stakeholder opening special url to see graph) as a trpc query. To start, let the "special code" just be an autogenerated ID made by the sql driver. The "create" endpoint should take nodes and edges, and return back the id of the newly created graph entry in the database. The "fetch" endpoint should take in an id and return the graph in the database.
3. Inside of the query page (*/pages/dashboard/datasets/[dataset_name]/query.tsx), let's add a hook to the body of the component i.e `const createGraphMutation = api.graphs.createGraph.useMutation()` and a button (imported from ant design). The onClick of the button should call `createGraphMutation.mutate({nodes: useGraphStore.getState().nodes, edges: useGraphStore.getState().edges})` to get the nodes and edges from the graph store and send it over to TRPC to handle. The `useMutation` hook takes an object `onSuccess` that'll be a function that executes once we've successfully saved the graph in our database. Inside there, we can show an alert (look for `messageApi` in the codebase for examples on how to do that). In fact, we can copy it to the user's clipboard automatically I believe [this goes over how to do that](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp). Note that there might be security checks by the browser to make sure that copy to clipboard is triggered by a user event (like a button click) so we might need to pop up a "Copy to clipboard" button with that as an onClick. The relevant string should be something like `http://localhost:3000/graph?id={GRAPH_ID_FROM_DATABASE}` (the exact url will depend on step 4.
4. Create a page to view graphs. Do this by creating a new component under the `pages` directory. The URL will map directly to the folder/file structure here. For simplicity, I recommend just creating a component `pages/graph.tsx`, which will make the page visible in `http://localhost:3000/graph`. This is the page the person who's trying to view the shared graph with open. In this page, use nextjs's [useRouter](https://nextjs.org/docs/api-reference/next/router#router-object) to access the id in the url with `router.query.id` to get the id, turn it into a number with the `+` operator if required by the `fetch` endpoint, then pass it into `const {data: {nodes, edges}} = api.graphs.getGraph({id})` and pass that into `<NetworkGraph nodes={nodes} edges={edges}/>` with the return of the component. The `NetworkGraph` component takes care of rendering.
5. Let me know if you need help! I'll do my best to get back to you as soon as possible. If you get stuck I'm here to help.
